version: "3.8"

services:
  webhook-server:
    image: webhook-server:v1.0.2
    restart: always
    ports:
      - "3000:3000"
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.webhook-server.rule=Host(`webhook.macedo.business`)
        - traefik.http.routers.webhook-server.entrypoints=websecure
        - traefik.http.routers.webhook-server.priority=1
        - traefik.http.routers.webhook-server.tls.certresolver=letsencryptresolver
        - traefik.http.services.webhook-server.loadbalancer.server.port=3000
        - traefik.http.services.webhook-server.loadbalancer.passHostHeader=1

networks:
  network_public:
    external: true
